name: Deploy Vite site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './vite-project/package.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./vite-project

      - name: Build
        run: npm run build
        working-directory: ./vite-project

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This points to the dist folder inside your subfolder
          path: ./vite-project/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4